name: pushbackend
on: push
env:
  java-version: '11'
  
jobs:
  build-and-deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - run: sam build
        working-directory: CloudResume
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: CloudResume
